language: python
notifications:
    on_success: never
    on_failure: always
python:
  - "3.6"
cache: pip3
install:
  - 'pip install -r requirements.txt'
  - 'pip install codecov'
os: "linux"
dist: "trusty"
addons:
  apt:
    packages:
      - python-coverage
script:
  - pytest
  - coverage run --source=tests/test_aic.py RegscorePy/aic.py 
  - coverage run --source=tests/test_bic.py RegscorePy/bic.py 
  - coverage run --source=tests/test_mallows.py RegscorePy/mallow.py 
after_success:
  - coverage combine
  - codecov

