language: python
notifications:
    on_success: never
    on_failure: always
python:
  - "3.6"
cache: pip3
install:
  - 'pip install -r requirements.txt'
  - 'pip install codecov'
  - 'python setup.py install'
os: "linux"
dist: "trusty"
addons:
  apt:
    packages:
      - python-coverage
script:
  - pytest
  - py.test tests/test_aic.py --cov=.RegscorePy
  - py.test tests/test_bic.py --cov=.RegscorePy
  - py.test tests/test_mallows.py --cov=.RegscorePy
after_success:
  - codecov

