language: python
notifications:
    on_success: never
    on_failure: always
python:
  - "3.6"
cache: pip3
install:
  - 'pip install -r requirements.txt'
  - 'pip install codecov'
  - 'pip install pytest-cov'
os: "linux"
dist: "trusty"
addons:
  apt:
    packages:
      - python-coverage
script:
  - pytest
  - py.test --cov=RegscorePy tests/ --cov-branch
  - coverage report -m 
after_success:
  - codecov

