language: python
notifications:
    on_success: never
    on_failure: always
python:
  - "3.6"
cache: pip3
install:
  - 'pip install -r requirements.txt'
  - 'pip install codecov'
  - 'pip install pytest-cov'
os: "linux"
dist: "trusty"
addons:
  apt:
    packages:
      - python-coverage
script:
  - pytest
  - py.test tests/test_aic.py --cov=RegscorePy/aic.py --cov-report=
  - coverage report -m
#  - coverage run --source=RegscorePy/aic.py tests/test_aic.py 
#  - coverage run --source=RegscorePy/bic.py tests/test_bic.py 
#  - coverage run --source=RegscorePy/mallow.py tests/test_mallows.py  
after_success:
  - coverage combine
  - codecov

