language: python
notifications:
    on_success: never
    on_failure: always
python:
  - "3.6"
cache: pip3
install:
  - 'pip install -r requirements.txt'
  - 'pip install codecov'
script:
  - pytest
  - py.test tests/test_aic.py tests/test_bic.py tests/test_mallows.py --cov=codecov
os: "linux"
dist: "trusty"
addons:
  apt:
    packages:
      - python-coverage
after_success:
  - codecov

