language: python
python:
  - "3.6"
cache: pip3
install:
  - 'pip install -r requirements.txt'
  - 'pip install codecov'
script:
  - pytest
os: "linux"
dist: "trusty"
notifications:
    on_success: never
    on_failure: never
after_success:
  - codecov
