language: python
notifications:
    on_success: never
    on_failure: always
python:
  - "3.6"
cache: pip3
install:
  - 'pip install -r requirements.txt'
  - 'pip install codecov'
os: "linux"
dist: "trusty"
addons:
  apt:
    packages:
      - python-coverage
script:
  - pytest
  - coverage run --source=tests test_aic.py test
  - coverage run --source=tests test_bic.py test
  - coverage run --source=tests test_mallows.py test
after_success:
  - coverage combine
  - codecov

